batch_size: 32
learning_rate: 0.001
epochs: 10
training_dataset: use_cases/train.csv
validation_dataset: use_cases/test.csv
training_name: my_training
output_dir: outputs/${training_name}_${now:%Y-%m-%d-%H-%M-%S}

hydra:
  run:
    dir: ${output_dir}
